# real test yml file
name: Test GitHub Action

# deployment_status
on: [push]
jobs: 
    build-app:
      runs-on: ubuntu-latest # runs on a docker container
      steps: 
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v4
            with:
              node-version: '14.17.0'
          - name: Build the Project
            run:  yarn build
          - name: Setup Finish
            run: echo "Actions completed"

